---
functional:
  - Должна быть реальзована возможность регистрации пользователя, с возможностью входа через Github и Discord
  - Должна быть реализована возможность входа для уже зарегистрированных пользователей
  - Должна быть реализована возможность востановления пароля на странице входа пользователя
  - 
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Логотип компании должен распологаться слева в шапке сайта
  - При нажатии на логотоп компании должена открываться "Главная страница"
  - На стартовой страницы сайта должна находиться краткая информация о сайте, языки программирования используемые в игре
  - При наведение курсором мыши на кнопки, они должны подсвечиваться
