---
functional:
  - Должна быть реальзована возможность регистрации пользователя, с возможностью входа через Github и Discord
  - Должна быть реализована возможность входа для уже зарегистрированных пользователей
  - Должна быть реализована возможность востановления пароля на странице входа пользователя
  - На главной странице должен быть реализован общий чат пользователей
  - У пользователя должна быть возможность создавать лобби
  - У пользователя должна быть возможность присоединятся к лобби
  - У пользователя должна быть возможность учавствовать в турнирах
  - У пользователя должна быть возможность посмотреть историю игр
  - При создании лобби пользователь должен иметь возможность выбрать сложность игры
  - При создании лобби пользователь должен иметь возможность выбора с кем играть (с другим пользователем, с другом, с ботом)
  - При создании лобби пользователь должен иметь возможность выбора времени игры
  - При создании лобби пользователь должен иметь возможность выбора задачи
  - Игра должна быть на следующих языках программирования: Clojure, C#, Dart, Elixir, Golang, Haskell, Java, Node.js, Kotlin, Php, Pithon, Ruby, Rust, Typescript
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика, 1000 пользователей одновременно
  - В шапке главной странице должно отображаться количество пользователей онлайн  
  - При заходе в игру открывается гайд по игре
  - В игре можно выбрать у задания язык, русский или английский 
implicit:
  - Логотип компании должен распологаться слева в шапке сайта
  - При нажатии на логотоп компании должена открываться "Главная страница"
  - На стартовой страницы сайта должна находиться краткая информация о сайте, языки программирования используемые в игре
  - При наведение курсором мыши на кнопки, они должны подсвечиваться
